spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db?encoding=utf8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6380

notification:
  stream:
    key: "notification:stream"
    group: "notification-group"
    consumer: "consumer-1"